// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflW_fkTiF55TSC5Bm4FnaOLDT8dfHeSc',
    appId: '1:744617258306:web:556c978e2495a8705aacdb',
    messagingSenderId: '744617258306',
    projectId: 'lh-virtual-store',
    authDomain: 'lh-virtual-store.firebaseapp.com',
    databaseURL: 'https://lh-virtual-store-default-rtdb.firebaseio.com',
    storageBucket: 'lh-virtual-store.appspot.com',
    measurementId: 'G-PL554GQFWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA56GsLqttyNX1fHzNKNFyKVhBz4LBcnjs',
    appId: '1:744617258306:android:a72de8bf4d7aa86a5aacdb',
    messagingSenderId: '744617258306',
    projectId: 'lh-virtual-store',
    databaseURL: 'https://lh-virtual-store-default-rtdb.firebaseio.com',
    storageBucket: 'lh-virtual-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICovZIfrUIS6hPRQzn3qPL3xOAqcyJBA',
    appId: '1:744617258306:ios:488d3124edc612705aacdb',
    messagingSenderId: '744617258306',
    projectId: 'lh-virtual-store',
    databaseURL: 'https://lh-virtual-store-default-rtdb.firebaseio.com',
    storageBucket: 'lh-virtual-store.appspot.com',
    iosClientId: '744617258306-jgv9q9feep0h76tj66deup79tvtmqr1s.apps.googleusercontent.com',
    iosBundleId: 'lighthousegeek.com.br.lhVirtualStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICovZIfrUIS6hPRQzn3qPL3xOAqcyJBA',
    appId: '1:744617258306:ios:488d3124edc612705aacdb',
    messagingSenderId: '744617258306',
    projectId: 'lh-virtual-store',
    databaseURL: 'https://lh-virtual-store-default-rtdb.firebaseio.com',
    storageBucket: 'lh-virtual-store.appspot.com',
    iosClientId: '744617258306-jgv9q9feep0h76tj66deup79tvtmqr1s.apps.googleusercontent.com',
    iosBundleId: 'lighthousegeek.com.br.lhVirtualStore',
  );
}
